apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: helloworld
spec:
  containers:
  - name: demo
    image: k8s.gcr.io/echoserver:1.4
    ports:
    - name: echo-port
      containerPort: 8080