apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo2
  labels:
    app: demo2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo2
  template:
    metadata:
      labels:
        app: demo2
    spec:
      containers:
      - name: demo2
        image: jocatalin/kubernetes-bootcamp:v2
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: demo2
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: demo2